# Is not a multi-arch image, so --platform=linux/amd64 throws a warning
FROM eclipse-temurin:21-jre-jammy
VOLUME /tmp

# Copy the pre-built JAR from the host machine
COPY ./target/TradeGuardServer-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"] 