# Is not a multi-arch image, so --platform=linux/amd64 throws a warning
ARG BUILD_PLATFORM
FROM --platform=${BUILD_PLATFORM} bellsoft/liberica-runtime-container:jre-21-slim-musl
VOLUME /tmp

# Copy the pre-built JAR from the host machine
COPY ./target/TradeGuardServer-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"] 